# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgUhLceYGdx9HEnPOY8OP60qFgCU574q
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
import time
import pandas as pd

import zipfile
import os

zip_path = "archive.zip"     # your uploaded file
extract_path = "dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")
print(os.listdir(extract_path))

import os

for root, dirs, files in os.walk("dataset"):
    print(root)
    print(dirs)
    break

#  Image Data Generators

from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# Data augmentation for training
train_datagen = ImageDataGenerator(
    rescale=1./255,              # normalize pixels (0-255 → 0-1)
    rotation_range=20,           # random rotation
    width_shift_range=0.2,       # horizontal shift
    height_shift_range=0.2,      # vertical shift
    zoom_range=0.2,              # random zoom
    horizontal_flip=True,        # flip image
    validation_split=0.2         # 80% train / 20% validation
)

# Training generator
train_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

# Validation generator
val_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

print("Class indices:", train_generator.class_indices)

#  Compute Class Weights (very important for medical datasets)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Get labels from training generator
train_labels = train_generator.classes

# Compute balanced weights
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_labels),
    y=train_labels
)

# Convert to dictionary
class_weight_dict = dict(enumerate(class_weights))

print("Class weights:", class_weight_dict)

CLASS_NAMES = ["benign", "malignant", "normal"]
NUM_CLASSES = len(CLASS_NAMES)

print("Number of classes:", NUM_CLASSES)

# Build CNN Model using EfficientNetB0

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers
from tensorflow import keras

# Load pretrained EfficientNet (without top classifier)
base_model = EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(224,224,3),
    pooling="avg"
)

# Freeze base model (first training phase)
base_model.trainable = False

# Build full model
model = keras.Sequential([
    base_model,                       # feature extractor
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

# Compile model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss="categorical_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

model.summary()

"""model.fit()-Starts learning.

train_generator-Feeds augmented training images.

validation_data-Checks performance on unseen validation images.
epochs=15

Model sees entire dataset 15 times.
class_weight
Fixes class imbalance (medical datasets usually imbalanced).
"""

#  Train model (Phase 1 – frozen EfficientNet)

print("Phase 1: Training classifier head only...\n")

history_phase1 = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,
    class_weight=class_weight_dict,
    verbose=1
)

"""Now EfficientNet adapts to:
Ultrasound textures
Tumor patterns
Medical features
"""

#  Fine-Tuning Phase

print("\nPhase 2: Fine-tuning EfficientNet...\n")

# Unfreeze entire base model
base_model.trainable = True

# Freeze early layers (keep last ~40 layers trainable)
for layer in base_model.layers[:-40]:
    layer.trainable = False

# Re-compile with lower learning rate
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-5),  # very small LR
    loss="categorical_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

# Train again
history_phase2 = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,
    class_weight=class_weight_dict,
    verbose=1
)

#  Model Evaluation

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# Get predictions from validation set
y_pred_prob = model.predict(val_generator)

# Convert probabilities to class labels
y_pred = np.argmax(y_pred_prob, axis=1)

# True labels
y_true = val_generator.classes

# Class names
class_names = list(val_generator.class_indices.keys())

"""Confusion Matrix"""

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

"""Classification Report"""

print("Classification Report:\n")

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names
))

"""ROC Curve & AUC Score

We evaluated diagnostic performance using ROC curves and AUC scores to measure the model’s ability to distinguish between benign, malignant, and normal cases.
"""

# ROC Curve and AUC Score

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np

# True labels
y_true = val_generator.classes

# Convert labels to binary format
y_true_bin = label_binarize(y_true, classes=np.arange(len(class_names)))

# Predicted probabilities from model
y_pred_prob = model.predict(val_generator)

plt.figure(figsize=(7,6))

for i in range(len(class_names)):

    # Compute ROC curve
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred_prob[:, i])

    # Compute AUC
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f"{class_names[i]} (AUC = {roc_auc:.2f})")

# Random guess line
plt.plot([0,1],[0,1],'k--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve (Medical Diagnosis Performance)")
plt.legend()
plt.show()

"""Grad-CAM Function"""

# Grad-CAM Function

import tensorflow as tf
import cv2
import numpy as np
import matplotlib.pyplot as plt

def get_gradcam_heatmap(img_array, base_model, last_conv_layer_name):

    # Model that outputs feature maps and predictions
    grad_model = tf.keras.models.Model(
        [base_model.input],
        [base_model.get_layer(last_conv_layer_name).output, base_model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        class_idx = tf.argmax(predictions[0])
        loss = predictions[:, class_idx]

    # Compute gradients
    grads = tape.gradient(loss, conv_outputs)

    # Global average pooling of gradients
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]

    # Create heatmap
    heatmap = tf.reduce_sum(tf.multiply(pooled_grads, conv_outputs), axis=-1)

    heatmap = np.maximum(heatmap, 0)

    if np.max(heatmap) != 0:
        heatmap /= np.max(heatmap)

    return heatmap

# Take one image from validation generator
sample_img, sample_label = next(val_generator)

img = sample_img[0:1]   # select first image

# EfficientNet last convolution layer
last_conv_layer = "top_conv"

# Generate heatmap
heatmap = get_gradcam_heatmap(img, base_model, last_conv_layer)

plt.figure(figsize=(10,5))

# Original Image
plt.subplot(1,2,1)
plt.imshow(sample_img[0])
plt.title("Original Image")
plt.axis("off")

# Heatmap overlay
plt.subplot(1,2,2)
plt.imshow(sample_img[0])
plt.imshow(cv2.resize(heatmap, (224,224)), cmap='jet', alpha=0.5)
plt.title("Grad-CAM (Model Focus)")
plt.axis("off")

plt.show()

